name: Reporte de Error
description: Crea un reporte para ayudarnos a mejorar
title: "[Error]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ¡Gracias por tomarte el tiempo de completar este reporte de error!
  - type: textarea
    id: what-happened
    attributes:
      label: ¿Qué sucedió?
      description: También cuéntanos, ¿qué esperabas que sucediera?
      placeholder: ¡Cuéntanos qué ves!
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Navegadores
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Otro
  - type: textarea
    id: reproduction
    attributes:
      label: Pasos para Reproducir
      description: ¿Cómo reproducimos este error?
      placeholder: |
        1. Ir a '...'
        2. Hacer clic en '...'
        3. Desplazarse hacia abajo hasta '...'
        4. Ver el error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Salida de logs relevante
      description: Por favor, copia y pega cualquier salida de log relevante. Esto se formateará automáticamente como código, por lo que no es necesario usar comillas invertidas.
      render: shell
