name: Solicitud de Funcionalidad
description: Sugiere una idea para este proyecto
title: "[Funcionalidad]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ¡Gracias por sugerir una idea! Por favor, explica tu solicitud de funcionalidad a continuación.
  - type: textarea
    id: problem
    attributes:
      label: ¿Tu solicitud de funcionalidad está relacionada con un problema? Por favor, descríbelo.
      description: Una descripción clara y concisa de cuál es el problema. Ej. Siempre me frustro cuando [...]
      placeholder: Siempre me frustro cuando...
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe la solución que te gustaría
      description: Una descripción clara y concisa de lo que quieres que suceda.
      placeholder: Me gustaría un botón que...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe las alternativas que has considerado
      description: Una descripción clara y concisa de cualquier solución o funcionalidad alternativa que hayas considerado.
      placeholder: Pensé en usar...
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Contexto adicional
      description: Agrega cualquier otro contexto o capturas de pantalla sobre la solicitud de funcionalidad aquí.
      placeholder: Aquí hay una captura de pantalla de una funcionalidad similar...
